/**
 * Icônes : une seule famille (Phosphor), un seul graisse (regular), importée depuis l'entrée SSR
 * pour fonctionner dans les composants serveur comme client. Aucun SVG dessiné à la main.
 */
export {
  Armchair,
  ArrowRight,
  ArrowLeft,
  ArrowUpRight,
  Article,
  Bell,
  Buildings,
  CalendarBlank,
  CalendarCheck,
  CaretDown,
  CaretLeft,
  CaretRight,
  Chair,
  ChartLineUp,
  ChatCircleText,
  Check,
  CheckCircle,
  Clock,
  ClockCountdown,
  CreditCard,
  Couch,
  CurrencyCircleDollar,
  DotsThreeVertical,
  Envelope,
  Eye,
  FileText,
  Flower,
  ForkKnife,
  Gauge,
  Gear,
  GearSix,
  HandCoins,
  Handshake,
  Heart,
  HardHat,
  House,
  Image as ImageIcon,
  Info,
  Lightbulb,
  List,
  LockKey,
  MagnifyingGlass,
  MapPin,
  Package,
  Pencil,
  Phone,
  Plus,
  Minus,
  Receipt,
  ShieldCheck,
  ShoppingCart,
  SignIn,
  SignOut,
  SlidersHorizontal,
  SpeakerHigh,
  Star,
  Storefront,
  Tag,
  Tent,
  Trash,
  TrendUp,
  Truck,
  UploadSimple,
  User,
  UserCircle,
  Users,
  Warning,
  WarningCircle,
  Wrench,
  X,
  ArrowsClockwise,
  ArrowCounterClockwise,
  Bank,
  Camera,
  ClipboardText,
  Coins,
  Fire,
  IdentificationCard,
  Key,
  Lifebuoy,
  Percent,
  Scales,
  Siren,
  Stack,
  Wallet,
  Money,
} from "@phosphor-icons/react/dist/ssr";

import {
  Armchair as ArmchairIcon,
  Chair as ChairIcon,
  Couch as CouchIcon,
  Flower as FlowerIcon,
  ForkKnife as ForkKnifeIcon,
  HardHat as HardHatIcon,
  Lightbulb as LightbulbIcon,
  Package as PackageIcon,
  SpeakerHigh as SpeakerHighIcon,
  Tent as TentIcon,
  Truck as TruckIcon,
  Wrench as WrenchIcon,
} from "@phosphor-icons/react/dist/ssr";
import type { Icon } from "@phosphor-icons/react";

/** Icônes de catégories : le nom est stocké en base (Category.icon). */
const CATEGORY_ICONS: Record<string, Icon> = {
  Armchair: ArmchairIcon,
  Chair: ChairIcon,
  Tent: TentIcon,
  ForkKnife: ForkKnifeIcon,
  SpeakerHigh: SpeakerHighIcon,
  Lightbulb: LightbulbIcon,
  Flower: FlowerIcon,
  Couch: CouchIcon,
  HardHat: HardHatIcon,
  Wrench: WrenchIcon,
  Truck: TruckIcon,
  Package: PackageIcon,
};

export function CategoryIcon({ name, size = 22, className }: { name?: string | null; size?: number; className?: string }) {
  const Cmp = (name && CATEGORY_ICONS[name]) || PackageIcon;
  return <Cmp size={size} weight="regular" className={className} aria-hidden />;
}
